// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOrcn9oiGzGOFDBNMtqxJvzBye6RMcF_0',
    appId: '1:1096335138828:web:1e1bf5bf8a011083da0e29',
    messagingSenderId: '1096335138828',
    projectId: 'calm-seeker-348402',
    authDomain: 'calm-seeker-348402.firebaseapp.com',
    databaseURL: 'https://calm-seeker-348402-default-rtdb.firebaseio.com',
    storageBucket: 'calm-seeker-348402.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrHAtsFwsc4F_7s_B-DFP8EcfB0bwLSwo',
    appId: '1:1096335138828:android:08a8f807eecebce9da0e29',
    messagingSenderId: '1096335138828',
    projectId: 'calm-seeker-348402',
    databaseURL: 'https://calm-seeker-348402-default-rtdb.firebaseio.com',
    storageBucket: 'calm-seeker-348402.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATK1p2yiXTjGep9Ro_LW8LvBlwI9uX8pY',
    appId: '1:1096335138828:ios:1649bc6b7d6618f0da0e29',
    messagingSenderId: '1096335138828',
    projectId: 'calm-seeker-348402',
    databaseURL: 'https://calm-seeker-348402-default-rtdb.firebaseio.com',
    storageBucket: 'calm-seeker-348402.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATK1p2yiXTjGep9Ro_LW8LvBlwI9uX8pY',
    appId: '1:1096335138828:ios:8a92e597ebff10e0da0e29',
    messagingSenderId: '1096335138828',
    projectId: 'calm-seeker-348402',
    databaseURL: 'https://calm-seeker-348402-default-rtdb.firebaseio.com',
    storageBucket: 'calm-seeker-348402.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
